"""
Streamlit App for Client Data Entry to Snowflake
Database: INCUBEX_DATA_LAKE / CLIENTS / CLIENTS
"""

import streamlit as st
import snowflake.connector
from datetime import date, datetime
import pandas as pd

# Page configuration
st.set_page_config(
    page_title="Client Data Entry",
    page_icon="📊",
    layout="centered"
)

# Custom CSS for better styling
st.markdown("""
    <style>
    .main-header {
        font-size: 3rem;
        font-weight: bold;
        color: #1E3A5F;
        margin-bottom: 0.5rem;
    }
    .sub-header {
        font-size: 1.8rem;
        font-weight: 600;
        color: #2E4A6F;
        margin-top: 1.5rem;
        margin-bottom: 1rem;
    }
    .success-box {
        padding: 1rem;
        background-color: #d4edda;
        border-radius: 5px;
        border: 1px solid #c3e6cb;
    }
    /* Submit button styling */
    div.stFormSubmitButton {
        text-align: center !important;
    }
    div.stFormSubmitButton > button {
        background-color: #4CAF50 !important;
        color: white !important;
        font-weight: bold !important;
        min-width: 300px !important;
        width: 50% !important;
        border-radius: 8px !important;
        padding: 0.75rem 2rem !important;
        white-space: nowrap !important;
    }
    div.stFormSubmitButton > button:hover {
        background-color: #45a049 !important;
    }
    /* Client Type toggle button styling */
    div[data-testid="stHorizontalBlock"] .stButton > button {
        width: 100%;
        border-radius: 8px;
        padding: 0.5rem 1rem;
        font-weight: 600;
        transition: all 0.2s ease;
    }
    .client-type-label {
        font-size: 1rem;
        font-weight: 600;
        color: #2E4A6F;
        margin-bottom: 0.5rem;
    }
    /* Light pink background for required fields (Company and Client Type) */
    .required-field div[data-baseweb="select"] > div {
        background-color: #fff5f5 !important;
    }
    </style>
""", unsafe_allow_html=True)


def get_snowflake_connection(schema="CLIENTS"):
    """
    Create Snowflake connection using Streamlit secrets.
    For Streamlit Cloud deployment, secrets are stored in .streamlit/secrets.toml
    """
    try:
        conn = snowflake.connector.connect(
            user=st.secrets["snowflake"]["user"],
            password=st.secrets["snowflake"]["password"],
            account=st.secrets["snowflake"]["account"],
            warehouse=st.secrets["snowflake"]["warehouse"],
            database="INCUBEX_DATA_LAKE",
            schema=schema
        )
        return conn
    except Exception as e:
        st.error(f"Connection error: {str(e)}")
        return None


@st.cache_data(ttl=300)  # Cache for 5 minutes
def get_all_dropdown_lists():
    """
    Fetch all dropdown lists (companies, brokers, clearers) using a single connection.
    Returns a tuple of (companies, brokers, clearers).
    """
    companies = []
    brokers = []
    clearers = []

    try:
        conn = snowflake.connector.connect(
            user=st.secrets["snowflake"]["user"],
            password=st.secrets["snowflake"]["password"],
            account=st.secrets["snowflake"]["account"],
            warehouse=st.secrets["snowflake"]["warehouse"],
            database="INCUBEX_DATA_LAKE",
            schema="CLIENTS"
        )
        cursor = conn.cursor()

        # Fetch companies
        cursor.execute("SELECT COMPANY_NAME FROM COMPANY_NAMES ORDER BY COMPANY_NAME")
        companies = [row[0] for row in cursor.fetchall() if row[0]]

        # Fetch brokers
        cursor.execute("SELECT COMPANY_NAME FROM BROKER_NAMES ORDER BY COMPANY_NAME")
        brokers = [row[0] for row in cursor.fetchall() if row[0]]

        # Fetch clearers
        cursor.execute("SELECT DISTINCT COMPANY_NAME FROM CLEARERS ORDER BY COMPANY_NAME")
        clearers = [row[0] for row in cursor.fetchall() if row[0]]

        cursor.close()
        conn.close()

    except Exception as e:
        st.error(f"Error fetching dropdown lists: {str(e)}")

    return companies, brokers, clearers


def insert_client_data(data: dict) -> bool:
    """
    Insert client data into Snowflake CLIENTS table.
    UPDATE_ID and DATE are auto-generated by Snowflake.
    """
    conn = get_snowflake_connection()
    if conn is None:
        return False

    try:
        cursor = conn.cursor()

        insert_query = """
        INSERT INTO CLIENTS (
            CLIENT_STATUS, CLIENT_TYPE, COMPANY, SENSITIVITIES, BARRIERS,
            DECISION_MAKERS, OVERALL_VOLUME, EUA_VOLUME, GO_VOLUME,
            POWER_VOLUME, GAS_VOLUME, OTHER_PRODUCT_NOTES, ACCESS_TYPE,
            FRONT_END, FRONT_END_DETAILS, CLEARERS, BROKERS, ETRM, SOURCE, NOTES
        ) VALUES (
            %(client_status)s, %(client_type)s, %(company)s, %(sensitivities)s, %(barriers)s,
            %(decision_makers)s, %(overall_volume)s, %(eua_volume)s, %(go_volume)s,
            %(power_volume)s, %(gas_volume)s, %(other_product_notes)s, %(access_type)s,
            %(front_end)s, %(front_end_details)s, %(clearers)s, %(brokers)s, %(etrm)s, %(source)s, %(notes)s
        )
        """

        cursor.execute(insert_query, data)
        conn.commit()
        cursor.close()
        conn.close()
        return True

    except Exception as e:
        st.error(f"Insert error: {str(e)}")
        if conn:
            conn.close()
        return False


def main():
    st.markdown('<p class="main-header">📊 Client Data Entry Form</p>', unsafe_allow_html=True)
    st.markdown("Enter client information below to add to the database.")

    st.info("""
**Required fields:** Company and Client Type (marked with *)

**Note:** Resubmitting for an existing company will update the record.
""")

    st.markdown("---")

    # Initialize session state for company fields
    if 'company_selection' not in st.session_state:
        st.session_state.company_selection = "Select a company..."
    if 'new_company_name' not in st.session_state:
        st.session_state.new_company_name = ""

    # Initialize session state for clearers/brokers fields
    if 'clearers' not in st.session_state:
        st.session_state.clearers = []
    if 'add_new_clearer' not in st.session_state:
        st.session_state.add_new_clearer = False
    if 'additional_clearers' not in st.session_state:
        st.session_state.additional_clearers = ""
    if 'brokers' not in st.session_state:
        st.session_state.brokers = []
    if 'add_new_broker' not in st.session_state:
        st.session_state.add_new_broker = False
    if 'additional_brokers' not in st.session_state:
        st.session_state.additional_brokers = ""

    # Check if we need to reset fields (set by successful form submission)
    if st.session_state.get('reset_company_fields', False):
        st.session_state.company_selection = "Select a company..."
        st.session_state.new_company_name = ""
        st.session_state.clearers = []
        st.session_state.add_new_clearer = False
        st.session_state.additional_clearers = ""
        st.session_state.brokers = []
        st.session_state.add_new_broker = False
        st.session_state.additional_brokers = ""
        st.session_state.reset_company_fields = False

    # Show success message and balloons after rerun
    if st.session_state.get('show_success', False):
        st.success("Client data submitted successfully!")
        st.balloons()
        st.session_state.show_success = False

    # Fetch all dropdown lists using single connection
    company_list, broker_list, clearer_list = get_all_dropdown_lists()

    # Company selection outside form for dynamic behavior
    st.markdown('<div class="required-field">', unsafe_allow_html=True)
    company_selection = st.selectbox(
        "Company *",
        options=["Select a company...", "-- Enter new company --"] + company_list,
        index=0,
        key="company_selection",
        help="Select from list or choose 'Enter new company' to add a new prospect"
    )
    st.markdown('</div>', unsafe_allow_html=True)

    # Show text input if user wants to enter a new company
    if company_selection == "-- Enter new company --":
        company = st.text_input(
            "New Company Name *",
            placeholder="Enter company name...",
            key="new_company_name",
            help="Type the name of the new company/prospect"
        )
    else:
        company = company_selection

    # Clearers and Brokers outside form for dynamic checkbox behavior
    st.markdown('<p class="sub-header">Service Providers</p>', unsafe_allow_html=True)
    col1, col2 = st.columns(2)

    with col1:
        clearers = st.multiselect(
            "Clearers",
            options=clearer_list,
            key="clearers",
            help="Clearing firms used (select multiple)"
        )
        add_new_clearer = st.checkbox("Add new clearer not in list", key="add_new_clearer")
        if add_new_clearer:
            additional_clearers = st.text_input(
                "New Clearer(s)",
                placeholder="Enter new clearer names (comma-separated)",
                key="additional_clearers",
                help="Add clearers not in the list above"
            )
        else:
            additional_clearers = ""

    with col2:
        brokers = st.multiselect(
            "Brokers",
            options=broker_list,
            key="brokers",
            help="Brokers used (select multiple)"
        )
        add_new_broker = st.checkbox("Add new broker not in list", key="add_new_broker")
        if add_new_broker:
            additional_brokers = st.text_input(
                "New Broker(s)",
                placeholder="Enter new broker names (comma-separated)",
                key="additional_brokers",
                help="Add brokers not in the list above"
            )
        else:
            additional_brokers = ""

    # Create form
    with st.form("client_form", clear_on_submit=True):

        # Client Type selection
        st.markdown('<div class="required-field">', unsafe_allow_html=True)
        client_type = st.selectbox(
            "Client Type *",
            options=["Customer", "Clearer", "Broker"],
            index=None,
            placeholder="Select client type...",
            help="Select the type of client"
        )
        st.markdown('</div>', unsafe_allow_html=True)

        # Client Status
        client_status = st.selectbox(
            "Client Status",
            options=["Client", "Prospect", "Setting up"],
            index=None,
            placeholder="Select status...",
            help="Current status of the client"
        )

        st.markdown('<p class="sub-header">Trading Information</p>', unsafe_allow_html=True)

        # Trading Info
        col1, col2 = st.columns(2)

        with col1:
            sensitivities = st.multiselect(
                "Sensitivities",
                options=["Margin", "Fees", "Liquidity"],
                help="Key issues that direct flow (select multiple)"
            )

        with col2:
            barriers = st.multiselect(
                "Barriers",
                options=[
                    "ICE Default",
                    "Fees",
                    "Margin",
                    "Liquidity",
                    "IT Setup (us)",
                    "IT Setup (them)",
                    "Compliance",
                    "Risk",
                    "Onboarding/KYC"
                ],
                help="Barriers to trading (select multiple)"
            )

        # Decision Makers
        decision_makers = st.text_input(
            "Decision Makers",
            placeholder="e.g., Head of desk (John Smith)",
            help="Key decision makers"
        )

        st.markdown('<p class="sub-header">Volume Information</p>', unsafe_allow_html=True)
        st.caption("Client's total annual volumes across all exchanges. Enter volume range or exact number per product.")

        # EUA Volume - Range dropdown OR exact number input
        st.markdown("EUA Volume (Lots)")
        eua_col1, eua_col2 = st.columns(2)
        with eua_col1:
            eua_volume_range = st.selectbox(
                "Estimated Range",
                options=[None, "<2.5k", "2.5-5k", "5-10k", "10-20k", "20-50k", "50k+"],
                index=0,
                format_func=lambda x: "Select range..." if x is None else x,
                help="Select an estimated volume range"
            )
        with eua_col2:
            eua_volume_exact = st.number_input(
                "Exact Volume",
                min_value=0,
                value=None,
                help="Or enter exact volume in lots"
            )

        # GO Volume - Range dropdown OR exact number input
        st.markdown("GO Volume (Lots)")
        go_col1, go_col2 = st.columns(2)
        with go_col1:
            go_volume_range = st.selectbox(
                "Estimated Range",
                options=[None, "<2.5k", "2.5-5k", "5-10k", "10-20k", "20k+"],
                index=0,
                format_func=lambda x: "Select range..." if x is None else x,
                help="Select an estimated volume range",
                key="go_volume_range"
            )
        with go_col2:
            go_volume_exact = st.number_input(
                "Exact Volume",
                min_value=0,
                value=None,
                help="Or enter exact volume in lots",
                key="go_volume_exact"
            )

        # Other Products
        other_product_notes = st.text_area(
            "Other Product Notes",
            placeholder="e.g., CBAM index interest",
            help="Notes on other products e.g. UKETS, CBAM, US products"
        )

        st.markdown('<p class="sub-header">Access & Systems</p>', unsafe_allow_html=True)

        # Access Info
        col1, col2 = st.columns(2)

        with col1:
            access_type = st.selectbox(
                "Access Type",
                options=["NCM", "GCM", "DMA", "API", "Sponsored Access", "Voice", "Other"],
                index=None,
                placeholder="e.g. NCM",
                help="Type of market access"
            )

        with col2:
            etrm = st.selectbox(
                "ETRM",
                options=[
                    "Allegro",
                    "Amphora",
                    "Aspect",
                    "Brady (Igloo, Powerdesk, Crisk...)",
                    "Comcore",
                    "Eka",
                    "Endure",
                    "Entrade",
                    "Entrader",
                    "Ignite",
                    "Inatech",
                    "Lancelot",
                    "Molecule",
                    "Openlink",
                    "PCI",
                    "PexaOS",
                    "Triplepoint",
                    "Vuepoint"
                ],
                index=None,
                placeholder="Select ETRM system",
                help="Energy Trading Risk Management system"
            )


        # Front End Info
        col1, col2 = st.columns(2)

        with col1:
            front_end = st.multiselect(
                "Front End",
                options=["TT", "Trayport", "Touchpoint", "Manual Entry", "CQG"],
                help="Trading front-end systems (select multiple)"
            )

        with col2:
            front_end_details = st.text_input(
                "Front End Details",
                placeholder="Additional details...",
                help="Additional front-end details"
            )

        # Source
        source = st.selectbox(
            "Source",
            options=["Meeting", "Estimate", "Call"],
            index=None,
            placeholder="e.g. Meeting",
            help="Data source"
        )

        # Notes
        notes = st.text_area(
            "Notes",
            placeholder="Additional context and notes",
            help="Any additional information about the client"
        )

        st.markdown("---")

        # Submit button
        submitted = st.form_submit_button(label="**Submit**", width="stretch")

        if submitted:
            # Validation
            if not client_type:
                st.error("Client Type is required!")
            elif not company or company == "Select a company..." or company == "-- Enter new company --":
                st.error("Company name is required!")
            else:
                # Convert multi-select lists to comma-separated strings
                front_end_str = ", ".join(front_end) if front_end else None

                # Combine selected clearers with additional ones
                all_clearers = list(clearers) if clearers else []
                if additional_clearers:
                    all_clearers.extend([c.strip() for c in additional_clearers.split(",") if c.strip()])
                clearers_str = ", ".join(all_clearers) if all_clearers else None

                # Combine selected brokers with additional ones
                all_brokers = list(brokers) if brokers else []
                if additional_brokers:
                    all_brokers.extend([b.strip() for b in additional_brokers.split(",") if b.strip()])
                brokers_str = ", ".join(all_brokers) if all_brokers else None

                # Range to midpoint mapping
                range_midpoints = {
                    "<2.5k": 1250,      # midpoint of 0-2500
                    "2.5-5k": 3750,     # midpoint of 2500-5000
                    "5-10k": 7500,      # midpoint of 5000-10000
                    "10-20k": 15000,    # midpoint of 10000-20000
                    "20-50k": 35000,    # midpoint of 20000-50000
                    "50k+": 50000,      # representative value for 50k+
                    "20k+": 20000,      # legacy value for GO volume
                }

                # Process EUA volume - exact value takes priority, otherwise use range midpoint
                eua_volume = None
                if eua_volume_exact is not None and eua_volume_exact > 0:
                    eua_volume = eua_volume_exact
                    if eua_volume_range is not None:
                        st.info("Note: Using exact EUA volume value (range selection ignored)")
                elif eua_volume_range is not None:
                    eua_volume = range_midpoints.get(eua_volume_range)

                # Process GO volume - exact value takes priority, otherwise use range midpoint
                go_volume = None
                if go_volume_exact is not None and go_volume_exact > 0:
                    go_volume = go_volume_exact
                    if go_volume_range is not None:
                        st.info("Note: Using exact GO volume value (range selection ignored)")
                elif go_volume_range is not None:
                    go_volume = range_midpoints.get(go_volume_range)

                # Convert multiselect lists to comma-separated strings
                sensitivities_str = ", ".join(sensitivities) if sensitivities else None
                barriers_str = ", ".join(barriers) if barriers else None

                # Prepare data (no update_id or date - auto-generated in Snowflake)
                data = {
                    'client_status': client_status if client_status else None,
                    'client_type': client_type,
                    'company': company,
                    'sensitivities': sensitivities_str,
                    'barriers': barriers_str,
                    'decision_makers': decision_makers if decision_makers else None,
                    'overall_volume': None,
                    'eua_volume': eua_volume,
                    'go_volume': go_volume,
                    'power_volume': None,
                    'gas_volume': None,
                    'other_product_notes': other_product_notes if other_product_notes else None,
                    'access_type': access_type if access_type else None,
                    'front_end': front_end_str,
                    'front_end_details': front_end_details if front_end_details else None,
                    'clearers': clearers_str,
                    'brokers': brokers_str,
                    'etrm': etrm if etrm else None,
                    'source': source if source else None,
                    'notes': notes if notes else None
                }

                # Insert data
                if insert_client_data(data):
                    # Flag to reset company fields and show success on next rerun
                    st.session_state.reset_company_fields = True
                    st.session_state.show_success = True
                    st.rerun()
                else:
                    st.error("Failed to submit data. Please check your connection and try again.")


if __name__ == "__main__":
    main()
